# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VirtualSpace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VirtualSpace
#pod 'IQKeyboardManagerSwift', '6.3.0'
pod 'NKVPhonePicker'
pod 'XLPagerTabStrip', '~> 9.0'

end
