# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VirtualSpace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VirtualSpace
pod 'NKVPhonePicker'
pod 'XLPagerTabStrip', '~> 9.0'
pod "CTPanoramaView", "~> 1.5"

end
